[package]
name = "ready_to_rust_opengl"
version = "0.1.0"
authors = ["ZaninDavide <zanindavide02@gmail.com>"]
license = "MIT"
edition = "2018"
build = "build.rs"

[dependencies]
glutin = "0.24"

[build-dependencies]
gl_generator = "0.13"
